export const CLICK_UPDATE_VALUE = 'CLICK_UPDATE_VALUE';
export const CLICK_UPDATE_SUCCESS = 'CLICK_UPDATE_SUCCESS';
export const FETCH_QUESTIONS_REQUEST = 'FETCH_QUESTIONS_REQUEST';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';